###################################################################
# JDevs                        v1.1                        JHider #
# JHider                                                    JDevs #
###################################################################

version: 1.1

# Control the messages.
settings:
  # Insert hex or minimessage.
  # minimessage - for Paper, 1.18+.
  # hex - It works starting from version 1.16.5, but if your server is lower than this version, do not change anything.
  translate: hex
  # You can find out the language code by clicking on the link below and looking at the In-Game section.
  # https://minecraft.fandom.com/wiki/Language#Languages
  # Set true to enable locales for messages.
  # You can configure locales in the plugin folder where the locales. folder is located. You can create your own files.
  locales: false
  # Set true to make placeholders work in messages.
  placeholderAPI: false
  # Specify which worlds will be blocked for performing actions.
  worlds:
    # Specify the blocking type: NULL, WHITELIST, BLACKLIST
    type: "null"
    worlds:
      - "thisIsBadWorldD1"
      - "YesThlsIsbad"
  command:
    # Return the message about the unknown command.
    # For Paper and forks - 1.12+ | For Spigot - 1.7-1.11 (or less?) | spigot.yml or this
    unknown: true
  player:
    # Disable the default player's joining message.
    join: true
    # Disable the default player's exit message.
    quit: true
    # Death settings.
    deaths:
      # Disable the default player's death message.
      disabled: true
      # Enable the fast death function.
      fast: false
  # Specify which messages will work in this configuration.
  messages:
    # Specify true to allow the plugin to accept values from this config.
    # To make this work correctly, you need to apply the settings in the "command" and "player" sections.
    # Unknown command. From 1.7 (or less?)
    unknown: false
    # Join message.
    join: false
    # Quit message.
    quit: false
    # Death message.
    death: false
    # Respawn message.
    respawn: false
    # Achievement message.
    achievement: false
# Set up the message.
# This will only work if you have selected the plugin configuration mode.
# If you have enabled locales, the messages below will be displayed by default if the language is not set.
messages:
  # Actions:
  # [actionbar] message - Send the actionbar with your message. For 1.11+
  # [message] message - Send a message to the player.
  # [broadcast] message - Send a message to all players.
  # [log] message - Send a message to the console.
  # [player] command - Run the command on behalf of the player.
  # [teleport] world;x;y;z;yaw;pitch;delay - Teleport the player to the specified coordinates. The delay is measured in ticks.
  # [console] command - Run the command on behalf of the console.
  # [title] title;subtitle;fadeIn;stay;fadeOut - Send the title to the player. For 1.8+
  # [sound] sound;volume;pitch;delay - Perform a sound for the player. The delay is measured in ticks.
  # Search for sounds here: https://helpch.at/docs/$version$/org/bukkit/Sound.html
  # // Replace $version$ with the version of your server, for example: https://helpch.at/docs/1.8.8/org/bukkit/Sound.html
  # [effect] type;duration;amplifier;delay - Give the effect to the player. The delay and duration is measured in ticks.
  # Find the types of effects here: https://helpch.at/docs/$version$/org/bukkit/potion/PotionEffectType.html
  # [bossbar] message;color;type;time;style;flag - Send a bossbar to a player with a message for a specific time. For 1.9+
  # Types:
  # stop - The bossbar will disappear after the time you specified in time (seconds)
  # time - Bossbar will animate the time that is running out.
  # Functions:
  # %time% - Seconds left.
  # You can find all the functions like color, style, and flag here: https://helpch.at/docs/$version$/org/bukkit/boss/BossBar.html
  #
  # Info:
  # Messages sent to the console may not replace placeholders or perform certain actions above.
  # Built-in functions:
  # %player% - Get the player name.
  unknown:
    - "[message] Unknown command. Type &a/help &ffor help."
  join:
    - "[message] %player% is &ajoined!"
  quit:
    - "[log] %player% is quited..."
  death:
    - "[message] %player% is &cdead..."
  respawn:
    - "[message] %player% has been &crespawned!"
  achievement:
    - "[message] %player% get a &aAchievement!"