name: JHider
version: '1.2'
main: ru.mitriyf.jhider.JHider
author: Mitriyf
api-version: 1.13
folia-supported: true
softdepend: [ JPirates, PlaceholderAPI ]
description: "The plugin configures spigot messages."
commands:
  jhider:
    description: Reloading configs